version: '3.7'

services:
  defi-blockchain:
    image: defi/defichain:1.6.3
    ports:
      - "19554:19554"
    command: >
      defid
      -printtoconsole
      -rpcallowip=172.17.0.0/16
      -rpcbind=0.0.0.0
      -rpcuser=whale-rpcuser
      -rpcpassword=whale-rpcpassword
      -regtest=1
      -txnotokens=0
      -logtimemicros
      -txindex=1
      -acindex=1
      -amkheight=0
      -bayfrontheight=1
      -bayfrontgardensheight=2
      -clarkequayheight=3
      -dakotaheight=4
      -dakotacrescentheight=5

  defi-whale:
    build: .
    image: ghcr.io/defich/whale:latest
    ports:
      - "3000:3000"
    depends_on:
      - defi-blockchain
    environment:
      WHALE_DEFID_URL: http://whale-rpcuser:whale-rpcpassword@defi-blockchain:19554
      WHALE_NETWORK: regtest
