name: Publish

on:
  release:
    types: [ published, prereleased ]

jobs:
  docker:
    name: Docker
    runs-on: ubuntu-latest
    environment: Docker Release
    steps:
      - name: Set up Semver
        uses: actions/github-script@v4
        id: version
        with:
          script: |
            const semver = context.ref.replace('refs/tags/v', '')
            if (semver.match(/[0-9]\.[0-9]\.[0-9]/)) {
              return semver
            }

            throw new Error('not semver')
          result-encoding: string

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push
        uses: docker/build-push-action@v2
        with:
          push: true
          platforms: |
            linux/amd64
            linux/arm64
          tags: |
            ghcr.io/defich/whale:latest
            ghcr.io/defich/whale:${{ steps.version.outputs.result }}
